### ISSUE TITLE
Web Server Using Python

### ISSUE THREAD

**Issue by frakman1** [UInt2048/7.0#1]
This is not an issue, just a comment.

I used python one-liner to make a website to server the files locally. Something like this:

`sudo python3 -m http.server 80`

**Comment by UInt2048** [comment]
Interesting, both that you can do that and that somebody is actually looking at this repo!

Feel free to submit a pull request if there's anything about how to do this that you want to add to the README or how I can support this.

**Comment by frakman1** [comment]
Your repo is awesome! I've been trying to get an iPad 2 on iOS 7.x.x jailbroken but the official evasi0n jailbreak app that's still hosted on their website won't work because they won't host the related files. I tried several different workarounds I found online but none of them worked. I also couldn't find the `.ipa` file anywhere and the `curl` example I found online wouldn't work.

Anyway, I saw a comment pointing to your repo and it was a real life-saver! Thank you for making this available and for it working on both Windows and Mac. I really appreciate it!

**Comment by UInt2048** [comment]
No problem! I'd found out on The iPhone Wiki about the state of evasi0n7's website going down, resulting in people unable to jailbreak iOS 7.0.x, and ended up discovering the original patcher and that its website had gone down, too. Since the patch was a simple URL change with a hex editor, I pulled out mine and reuploaded everything. 😉 

As it turned out, I never actually ended up on iOS 7, and thus I never got to test this myself. I'm glad it's helped save some real iOS 7 devices though!

**Comment by frakman1** [comment]
How did you find the actual ipa by the way? Did you get it from Apple servers or somewhere else?

**Comment by UInt2048** [comment]
It says in the README where I got everything - the guy who patched evasi0n the first time reuploaded it, and I downloaded that via https://web.archive.org

**Comment by spockers** [comment]
> It says in the README where I got everything - the person that patched evasi0n the first time reuploaded it, and I downloaded that via https://web.archive.org

Well done, I didn’t realize my little site even got archived, that’s awesome.
